all:
    children:
        ubuntu:
            children:
                ubuntu2004:
                    hosts:
                        ubuntu.server.local:
                    vars:
                        ansible_python_interpreter=/usr/bin/python3
        centos:
            children:
                centos8:
                    hosts:
                        centos.server.local:
                    vars:
                        ansible_python_interpreter=/usr/bin/python3
