---
- hosts: ubuntu
  tasks:
  - name: Package installation
    apt:
      name:
        - rsync
        - wget
        - ca-certificates
        - vim-nox
      state: latest

  - name: Asegurarse de que existe el grupo "admin"
    ansible.builtin.group:
      name: admin
      state: present

  - name: Crear el usuario Administrador, asignarle el grupo, y crear una llave privada SSH
    ansible.builtin.user:
      name: administrador
      generate_ssh_key: yes
      ssh_key_bits: 4096
      ssh_key_file: ".ssh/id_rsa-{{ inventory_hostname }}"
      groups: admin, sudo
      shell: /bin/bash
      append: yes

  - name: Copiar archivo de llaves publicas
    copy:
      src: "{{ playbook_dir }}/../Files/authorized_keys"
      dest: "/home/administrador/.ssh/authorized_keys"
      backup: no
      owner: administrador
      group: administrador
      mode: 0600

  - name: Copiar archivo sudoers
    copy:
      src: "{{ playbook_dir }}/../Files/sudo/sudo_admin"
      dest: "/etc/sudoers.d/sudo_admin"
      backup: no
      owner: root
      group: root
