---
- hosts: ubuntu
  vars_prompt:
    - name: domain
      prompt: Domain to join?
      private: no

    - name: username
      prompt: Domain admin to join domain?
      private: no

    - name: password
      prompt: Domain admin password to join domain?
      unsafe: yes

  tasks:
  - name: Package installation for AD join
    apt:
      name:
        - sssd-ad
        - sssd-tools
        - realmd
        - adcli
        - krb5-user
        - sssd-krb5
      state: present

  - name: Enable SSSD service
    ansible.builtin.service:
      name: sssd
      enabled: yes

  - name: Copy sudoers files
    copy:
      src: "{{ playbook_dir }}/../Files/sudo/sudo_domain_admins"
      dest: "/etc/sudoers.d/sudo_domain_admins"
      backup: no

  - name: Join domain with adcli
    command: "echo {{ password }} | realm join --user={{ username }} {{ domain }} --unattended"

  - name: Allow given groups to authenticate
    command: "realm permit -g 'Domain Admins'"

  - name: Replace fully qualified names
    replace:
      path: /etc/sssd/sssd.conf
      regexp: '(\s+)use_fully_qualified_names = True'
      replace: "\nuse_fully_qualified_names = False"
      backup: no

  - name: Replace home directory policy
    replace:
      path:  /etc/sssd/sssd.conf
      regexp: '(\s+)fallback_homedir = /home/%u@%d'
      replace: "\nfallback_homedir = /home/%u"
      backup: no

  - name: Restart service aftes config change
    ansible.builtin.service:
      name: sssd
      state: restarted

  - name: Update authentications methods to allow Ad
    command: "authconfig --enablesssd --enablesssdauth --enablemkhomedir --update"
